name: hello-world
on: push
jobs: 
    hello-world-job:
    uses: ubuntu
     steps:
         - name: Check out repository code
           uses: action/checkout@v3
         - run: echo "$(cat hello_world.txt)"
